services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: nest-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - nest-postgres
      - redis
    env_file:
      - .env
    command: npm run start:dev
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

  nest-postgres:
    image: postgres:14
    container_name: nest-postgres
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - nest-postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: nest-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  nest-postgres:
    name: nest-postgres-db
  redis-data:
    name: nest-redis-data
